### PR TITLE
Updated Docker image paths in Simple4.yml

### PR DESCRIPTION
**Pull request by temucin**
Updated the simple4.yml so that the Docker images are correctly prefixed with "efblock/". Will work correctly now when run with compose.

### CODE REVIEW

**Comment by no2chem** [comment]
Thanks for the PR! Where does the efblock repository come from?

**Comment by temucin** [comment]
https://hub.docker.com/r/efblock/concord-truffle

I had assumed it was a VMWare owned.

**Comment by tompscanlan** [comment]
I think there's a miscommunication here.  The `simple4.yml` is intended to be used as in the the docs at https://concord.readthedocs.io/en/latest/getting-started.html, where images are built locally and run from the locally built images.  I don't think VMware has pushed public container images for these, so changing the compose file like this doesn't help as @temucin  is expecting.

Committing this as is will break docs, and use an unknown user's images if using docker-compose.

Is there any plan for VMware to host public images of concourse?  If so, then a similar change pointing at the VMware public registry would do what @temucin desires.

I think :)

**Comment by temucin** [comment]
@tompscanlan thats exactly what I was hoping. Was a bit confused when I realized the public containers where not VM Ware hosted.

I also see now the build_images script in the Docker resource, which I initially missed.

This can definitely be closed now. Thanks!

**Comment by no2chem** [comment]
Hi all, just a follow up on all of this - we don't have public docker images hosted yet, but it's something we're looking into for the future, we just need to add it to our publish flow.

**Pull request closed without merging**
